### ISSUE TITLE
Does not compile 

### ISSUE THREAD

**Issue by imzeeshan** [VladislavRUS/cityguide#1]
Hey, firstly, amazing demo.

I tried to compile and run this, but it gives me an error.

Does it need an older version of react native ??

**Comment by VladislavRUS** [comment]
Thanks, nice to hear it! 
Are you trying to build an apk? Demo was recorded via emulator in development mode so in fact i have never tried to build it. I usually use Expo for real apps, it makes building process more simple.

**Comment by imzeeshan** [comment]
@VladislavRUS Yes I am trying to build an apk, could you update the readme with steps ? 

I am trying to make you demo with real content, see http://icityconcierge.com/ , via an API or SQLite db. 

Thanks for your help.

**Comment by VladislavRUS** [comment]
@imzeeshan I was able to build a debug apk by running './gradlew assembleDebug' command in 'android' directory, try this. For release build there are instructions in https://facebook.github.io/react-native/docs/signed-apk-android
